// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_Examinationen.Models;

#nullable disable

namespace WebApi_Examinationen.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220828185517_orders.Designer")]
    partial class ordersDesigner
    {
    }
}
